### ISSUE TITLE
LRU (Least Recently Used) 알고리즘

### ISSUE THREAD

**Issue by dev-wooyeon** [crewcrew-coding-test-study/crewcrew-coding-test-study#33]
페이지 교체 알고리즘
> 페이지 부재가 발생 하여 새로운 페이지를 할당하기 위해 현재 할당된 페이지 중 어느 것과 교체할지를 결정하는 방법이다. 이 알고리즘이 사용되는 시기는 페이지 부재가 발생해 새로운 페이지를 적재 해야하나 페이지를 적재할 공간이 없어 이미 적재되어 있는 페이지 중 교체할 페이지를 정할 때 사용된다.

![image](https://user-images.githubusercontent.com/50124623/210241333-cb8e5fef-3741-4ab2-b539-70d637475ae8.png)

``` python
cacheSize = 3
reference = [4, 2, 3, 4, 5, 6, 5, 4, 7]
cache = []
for ref in reference:
  if not ref in cache:
    if len(cache) < cacheSize:
        cache.append(ref)
     else:
        cache.pop(0)
        cache.append(ref)
  else:
    cache.pop(cache.index(ref))
    cache.append(ref)
```

**Comment by Slowth-KIM** [comment]
deque의 popleft를 pop(0)으로 대체할 수 있습니다.
또한 cache.pop(cache.index(ref)) 대신 cashe.remove(값) 혹은 del cashe[인덱스]로도 사용할 수 있습니다.
